[project]
name = "bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "whatphilipcodes", email = "gerdes.philip@gmail.com" }]
dependencies = [
    "llama-benchy",
]

[tool.uv.sources]
llama-benchy = { git = "https://github.com/whatphilipcodes/llama-benchy", branch = "feat-strict-api" }
