services:
  sglang-node:
    image: vllm/vllm-openai:gemma4-0505-cu130
    container_name: VLLM-Gemma-4-E2B-it
    ipc: host
    cap_add:
      - SYS_NICE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864
    ports:
      - 8000:8000
    volumes:
      - /opt/huggingface_cache/hub:/root/.cache/huggingface/hub
    env_file:
      - ../.env
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - CUTE_DSL_ARCH=sm_121a
    command: >
      --model google/gemma-4-E2B-it
      --gpu-memory-utilization 0.7
      --max-model-len 131072
      --load-format safetensors
      --enable-prefix-caching
      --enable-auto-tool-choice
      --tool-call-parser gemma4
      --reasoning-parser gemma4
      --quantization fp8
      --kv-cache-dtype fp8
      --max-num-batched-tokens 8192
      -tp 1