x-shared: &shared
  extends:
    file: all-base.yaml
    service: base
    
  container_name: VLLM-Qwen-3-8-27B-NVFP4
  entrypoint: ["vllm", "serve"]
  command: >
    unsloth/Qwen3.8-27B-NVFP4

services:
  spark:
    <<: *shared
    image: eugr/spark-vllm-b12x:latest
    volumes:
      - /opt/huggingface_cache/hub:/root/.cache/huggingface/hub

  wsl:
    <<: *shared
    image: vllm/vllm-openai:latest
    environment:
      - VLLM_WSL2_ENABLE_PIN_MEMORY=1
    volumes:
      - /home/philip/.cache/huggingface/hub:/root/.cache/huggingface/hub