x-shared: &shared
  extends:
    file: all-base.yaml
    service: base
    
  container_name: VLLM-Gemma-4-26B-A4B-NVFP4
  entrypoint: ["vllm", "serve"]
  command: >
    nvidia/gemma-4-26B-A4B-NVFP4
    --gpu-memory-utilization 0.8
    --max-model-len 65536

services:
  spark:
    <<: *shared
    image: eugr/spark-vllm-b12x:latest
    volumes:
      - /opt/huggingface_cache/hub:/root/.cache/huggingface/hub

  wsl:
    <<: *shared
    image: vllm/vllm-openai:latest
    environment:
      - VLLM_WSL2_ENABLE_PIN_MEMORY=1
    volumes:
      - /home/philip/.cache/huggingface/hub:/root/.cache/huggingface/hub