x-shared: &shared
  extends:
    file: all-base.yaml
    service: base
    
  container_name: Nemotron-3-5-Lightning-30B-A3B-NVFP4
  entrypoint: ["vllm", "serve"]
  command: >
    nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-NVFP4
    --moe-backend marlin
    --kv-cache-dtype fp8
    --max-model-len 1048576
    --enable-prefix-caching
    --mamba-backend flashinfer
    --mamba-cache-mode align
    --speculative_config.method dspark
    --speculative_config.model nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-NVFP4-DSpark
    --speculative_config.num_speculative_tokens 3
    --gpu-memory-utilization 0.6

services:
  spark:
    <<: *shared
    image: eugr/spark-vllm-b12x:latest
    volumes:
      - /opt/huggingface_cache/hub:/root/.cache/huggingface/hub

  wsl:
    <<: *shared
    image: vllm/vllm-openai:latest
    environment:
      - VLLM_WSL2_ENABLE_PIN_MEMORY=1
    volumes:
      - /home/philip/.cache/huggingface/hub:/root/.cache/huggingface/hub