x-shared: &shared
  extends:
    file: all-base.yaml
    service: base
    
  container_name: VLLM-Gemma-4-E2B-it
  entrypoint: ["vllm", "serve"]
  command: >
    google/gemma-4-E2B-it
    --gpu-memory-utilization 0.85
    --max-model-len 8192
    --enable-prefix-caching
    --max-num-batched-tokens 8192
    --attention-backend flashinfer

services:
  spark:
    <<: *shared
    image: eugr/spark-vllm-b12x:latest
    environment:
      - CUTE_DSL_ARCH=sm_121a
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    volumes:
      - /opt/huggingface_cache/hub:/root/.cache/huggingface/hub

  wsl:
    <<: *shared
    image: vllm/vllm-openai:latest
    environment:
      - VLLM_WSL2_ENABLE_PIN_MEMORY=1
    volumes:
      - /home/philip/.cache/huggingface/hub:/root/.cache/huggingface/hub