[project]
name = "bench-sglang"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.13.0"
authors = [{ name = "whatphilipcodes", email = "gerdes.philip@gmail.com" }]
dependencies = [
  "sglang>=0.5.18",
  "sglang-kernel>=0.4.6.post1",
  "torchcodec>=0.16.0",
]

[project.scripts]
bench-sglang = "bench_sglang:main"

[dependency-groups]
dev = [
  "ruff>=0.16.2",
  "ty>=0.0.70",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
prerelease = "allow"
environments = ["sys_platform == 'linux' and platform_machine == 'aarch64'"]
# override-dependencies = ["transformers==5.12.1", "tokenizers==0.22.2"] # sglang pyproject.toml
# override-dependencies = ["transformers==5.16.1", "tokenizers==0.23.1"]

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchaudio = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
torchcodec = { index = "pytorch-cu130" }
sglang-kernel = { index = "sglang-cu130" }
sglang = { git = "https://github.com/sgl-project/sglang.git", subdirectory = "python", rev = "9a05b47" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "sglang-cu130"
url = "https://sgl-project.github.io/whl/cu130"
explicit = true
