[project]
name = "bench-vllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "whatphilipcodes", email = "gerdes.philip@gmail.com" }]
dependencies = [
  "vllm>=0.28.0",
  "vllm-gguf-plugin>=0.0.5",
]

[project.scripts]
bench-vllm = "bench_vllm:main"

[dependency-groups]
dev = [
  "ruff>=0.16.2",
  "ty>=0.0.70",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
prerelease = "allow"
environments = ["sys_platform == 'linux' and platform_machine == 'aarch64'"]

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchaudio = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
